# Generated by Django 6.0.6 on 2026-06-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convenios", "0002_replace_convenio_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="Esfera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concedente_cnpj",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="CNPJ do Concedente",
                    ),
                ),
                (
                    "concedente_esfera",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Esfera"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Esfera do Concedente",
                "verbose_name_plural": "Esferas dos Concedentes",
            },
        ),
        migrations.CreateModel(
            name="CodigoConvenio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "convenio_codigo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código do Convênio",
                    ),
                ),
                (
                    "convenio_codigo_sequencial",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código Sequencial",
                    ),
                ),
                (
                    "convenio_numero_sequencial_siafi",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nº Sequencial SIAFI",
                    ),
                ),
                (
                    "unidade_orcamentaria_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Unidade Orçamentária",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Mapeamento de Códigos do Convênio",
                "verbose_name_plural": "Mapeamentos de Códigos de Convênios",
                "indexes": [
                    models.Index(
                        fields=["convenio_codigo"], name="cod_convenio_codigo_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CodigoDeclaracaoContrapartida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "declaracao_contrapartida_codigo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código da Declaração",
                    ),
                ),
                (
                    "convenio_numero_sequencial_siafi",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nº Sequencial SIAFI",
                    ),
                ),
                (
                    "unidade_orcamentaria_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Unidade Orçamentária",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Mapeamento de Códigos da Declaração de Contrapartida",
                "verbose_name_plural": "Mapeamentos de Códigos de Declarações de Contrapartida",
                "indexes": [
                    models.Index(
                        fields=["declaracao_contrapartida_codigo"],
                        name="cod_decl_contrap_idx",
                    ),
                    models.Index(
                        fields=["convenio_numero_sequencial_siafi"],
                        name="cod_decl_siafi_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CodigoPlanoTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conveno_codigo_plano_trabalho",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código do Plano de Trabalho",
                    ),
                ),
                (
                    "convenio_numero_sequencial_siafi",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nº Sequencial SIAFI",
                    ),
                ),
                (
                    "unidade_orcamentaria_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Unidade Orçamentária",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Mapeamento de Códigos do Plano de Trabalho",
                "verbose_name_plural": "Mapeamentos de Códigos de Planos de Trabalho",
                "indexes": [
                    models.Index(
                        fields=["conveno_codigo_plano_trabalho"],
                        name="cod_plano_trabalho_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CodigoTermoAditivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "convenio_numero_sequencial_siafi",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nº Sequencial SIAFI",
                    ),
                ),
                (
                    "termo_aditivo_codigo_sequencial",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código Sequencial do Termo Aditivo",
                    ),
                ),
                (
                    "unidade_orcamentaria_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Unidade Orçamentária",
                    ),
                ),
                (
                    "plano_trabalho_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código do Plano de Trabalho",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Mapeamento de Códigos do Termo Aditivo",
                "verbose_name_plural": "Mapeamentos de Códigos de Termos Aditivos",
                "indexes": [
                    models.Index(
                        fields=["termo_aditivo_codigo_sequencial"],
                        name="cod_ta_sequencial_idx",
                    ),
                    models.Index(
                        fields=["convenio_numero_sequencial_siafi"],
                        name="cod_ta_siafi_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConvenioGeral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "convenio_codigo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código do Convênio",
                    ),
                ),
                (
                    "convenio_codigo_sequencial",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código Sequencial",
                    ),
                ),
                (
                    "conveno_codigo_plano_trabalho",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código Plano de Trabalho",
                    ),
                ),
                (
                    "convenio_numero_sequencial_siafi",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nº Sequencial SIAFI",
                    ),
                ),
                (
                    "convenio_codigo_declaracao",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código Declaração",
                    ),
                ),
                (
                    "convenio_data_de_publicacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Publicação"
                    ),
                ),
                (
                    "convenio_data_alteracao_sccg",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Alteração SCCG"
                    ),
                ),
                (
                    "convenio_data_controle_sccg_convenio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Controle SCCG"
                    ),
                ),
                (
                    "convenio_data_assinatura_convenio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Assinatura"
                    ),
                ),
                (
                    "convenio_data_de_cadastramento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Cadastramento"
                    ),
                ),
                (
                    "convenio_ano",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ano"
                    ),
                ),
                (
                    "convenio_alteracao",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Alteração"
                    ),
                ),
                (
                    "convenio_matricula_tecnico_sccg",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Matrícula Técnico SCCG",
                    ),
                ),
                (
                    "convenio_justificativa_da_alteracao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Justificativa da Alteração"
                    ),
                ),
                (
                    "convenio_matricula_gestor",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Matrícula Gestor",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Convênio — Dados Gerais",
                "verbose_name_plural": "Convênios — Dados Gerais",
                "indexes": [
                    models.Index(
                        fields=["convenio_codigo"], name="conv_geral_codigo_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CronogramaDesembolso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plano_trabalho_codigo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código do Plano de Trabalho",
                    ),
                ),
                (
                    "valor_concedente_cronograma_desembolso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Valor Concedente",
                    ),
                ),
                (
                    "valor_proponente_cronograma_desembolso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Valor Proponente",
                    ),
                ),
                (
                    "mes_cronograma_desembolso",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Mês"
                    ),
                ),
                (
                    "ano_cronograma_desembolso",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ano"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Cronograma de Desembolso",
                "verbose_name_plural": "Cronogramas de Desembolso",
                "indexes": [
                    models.Index(
                        fields=["plano_trabalho_codigo"],
                        name="cronograma_plano_codigo_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeclaracaoContrapartida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "declaracao_contrapartida_codigo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código da Declaração",
                    ),
                ),
                (
                    "declaracao_contrapartida_codigo_nota_tecnica",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código Nota Técnica",
                    ),
                ),
                (
                    "declaracao_contrapartida_codigo_parecer_aprovacao",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código Parecer de Aprovação",
                    ),
                ),
                (
                    "declaracao_contrapartida_data_completa_emissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Completa de Emissão"
                    ),
                ),
                (
                    "declaracao_contrapartida_data_emissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Emissão"
                    ),
                ),
                (
                    "declaracao_contrapartida_data_completa_parecer_aprovacao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data Completa Parecer Aprovação",
                    ),
                ),
                (
                    "declaracao_contrapartida_data_parecer_aprovacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Parecer Aprovação"
                    ),
                ),
                (
                    "declaracao_contrapartida_observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "declaracao_contrapartida_observacao_aprovacao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observação de Aprovação"
                    ),
                ),
                (
                    "declaracao_contrapartida_ano",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ano"
                    ),
                ),
                (
                    "declaracao_contrapartida_status",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Status"
                    ),
                ),
                (
                    "declaracao_contrapartida_matricula_aprovacao",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Matrícula Aprovação",
                    ),
                ),
                (
                    "declaracao_contrapartida_momento",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Momento"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Declaração de Contrapartida",
                "verbose_name_plural": "Declarações de Contrapartida",
                "indexes": [
                    models.Index(
                        fields=["declaracao_contrapartida_codigo"],
                        name="decl_contrap_codigo_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NtEmenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unidade_orcamentaria_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Unidade Orçamentária",
                    ),
                ),
                (
                    "plano_trabalho_codigo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código do Plano de Trabalho",
                    ),
                ),
                (
                    "nt_emenda_no",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nº NT Emenda",
                    ),
                ),
                (
                    "nt_emenda_nome",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome NT Emenda",
                    ),
                ),
                (
                    "nota_tecnica_emenda_parlamentar_federal_situacao",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Situação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "NT Emenda Parlamentar",
                "verbose_name_plural": "NTs Emendas Parlamentares",
                "indexes": [
                    models.Index(
                        fields=["plano_trabalho_codigo"],
                        name="nt_emenda_plano_codigo_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanoAplicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_plano_trabalho",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código do Plano de Trabalho",
                    ),
                ),
                (
                    "codigo_unidade_orcamentaria",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Unidade Orçamentária",
                    ),
                ),
                (
                    "funcao_codigo",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Cód. Função"
                    ),
                ),
                (
                    "subfuncao_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Subfunção",
                    ),
                ),
                (
                    "programa_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Programa",
                    ),
                ),
                (
                    "identificador_projeto_atividade_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Identificador Projeto/Atividade",
                    ),
                ),
                (
                    "projeto_atividade_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Projeto/Atividade",
                    ),
                ),
                (
                    "subprojeto_subatividade_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Subprojeto/Subatividade",
                    ),
                ),
                (
                    "categoria_economica_despesa_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Categoria Econômica",
                    ),
                ),
                (
                    "grupo_despesa_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Grupo de Despesa",
                    ),
                ),
                (
                    "modalidade_aplicacao_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Modalidade de Aplicação",
                    ),
                ),
                (
                    "elemento_despesa_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Elemento de Despesa",
                    ),
                ),
                (
                    "identificador_orcamento_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Identificador Orçamento",
                    ),
                ),
                (
                    "fonte_recurso_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Fonte de Recurso",
                    ),
                ),
                (
                    "procedencia_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. Procedência",
                    ),
                ),
                (
                    "funcional_programatica_formatado",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Funcional Programática",
                    ),
                ),
                (
                    "valor_concedente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Valor Concedente",
                    ),
                ),
                (
                    "valor_proponente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Valor Proponente",
                    ),
                ),
                (
                    "ano_exercicio_programa_trabalho",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ano Exercício",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Plano de Aplicação",
                "verbose_name_plural": "Planos de Aplicação",
                "indexes": [
                    models.Index(
                        fields=["codigo_plano_trabalho"],
                        name="plano_aplicacao_codigo_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanoTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plano_trabalho_codigo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código do Plano de Trabalho",
                    ),
                ),
                (
                    "plano_trabalho_codigo_execucao_no_exercicio",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código Execução no Exercício",
                    ),
                ),
                (
                    "plano_trabalho_tipo_siafi",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Tipo SIAFI"
                    ),
                ),
                (
                    "plano_trabalho_cnpj_concedente",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="CNPJ Concedente",
                    ),
                ),
                (
                    "plano_trabalho_cnpj_proponente",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="CNPJ Proponente",
                    ),
                ),
                (
                    "plano_trabalho_data_cancelamento_sccg",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Cancelamento SCCG"
                    ),
                ),
                (
                    "plano_trabalho_data_cadastro",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "plano_trabalho_data_envio_sccg",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Envio SCCG"
                    ),
                ),
                (
                    "plano_trabalho_titulo",
                    models.TextField(blank=True, null=True, verbose_name="Título"),
                ),
                (
                    "plano_trabalho_objeto",
                    models.TextField(blank=True, null=True, verbose_name="Objeto"),
                ),
                (
                    "plano_trabalho_justificativa",
                    models.TextField(
                        blank=True, null=True, verbose_name="Justificativa"
                    ),
                ),
                (
                    "plano_trabalho_status",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Status"
                    ),
                ),
                (
                    "plano_trabalho_caracteristica",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Característica",
                    ),
                ),
                (
                    "plano_trabalho_tipo",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Tipo"
                    ),
                ),
                (
                    "plano_trabalho_migrado_ou_novo",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Migrado ou Novo",
                    ),
                ),
                (
                    "plano_trabalho_matricula_sccg_cancelamento",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Matrícula SCCG Cancelamento",
                    ),
                ),
                (
                    "plano_trabalho_justificativa_sccg_cancelamento",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Justificativa SCCG Cancelamento",
                    ),
                ),
                (
                    "plano_trabalho_cancelamento_sccg",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Cancelamento SCCG",
                    ),
                ),
                (
                    "plano_trabalho_ano",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ano"
                    ),
                ),
                (
                    "plano_trabalho_altera_termo_aditivo",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Altera Termo Aditivo",
                    ),
                ),
                (
                    "plano_trabalho_razao_social_concedente",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Razão Social Concedente",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Plano de Trabalho",
                "verbose_name_plural": "Planos de Trabalho",
                "indexes": [
                    models.Index(
                        fields=["plano_trabalho_codigo"],
                        name="plano_trabalho_codigo_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProrrogacaoOficio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prorrogacao_oficio_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código da Prorrogação",
                    ),
                ),
                (
                    "prorrogacao_oficio_codigo_convenio",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código do Convênio",
                    ),
                ),
                (
                    "prorrogacao_oficio_data_inicio_vigencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Início de Vigência"
                    ),
                ),
                (
                    "prorrogacao_oficio_data_termino_vigencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Término de Vigência"
                    ),
                ),
                (
                    "prorrogacao_oficio_data_envio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Envio"
                    ),
                ),
                (
                    "prorrogacao_oficio_data_parecer",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Parecer"
                    ),
                ),
                (
                    "prorrogacao_oficio_data_publicacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Publicação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Prorrogação de Ofício",
                "verbose_name_plural": "Prorrogações de Ofício",
                "indexes": [
                    models.Index(
                        fields=["prorrogacao_oficio_codigo_convenio"],
                        name="prorrogacao_conv_codigo_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TermoAditivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "termo_aditivo_codigo_sequencial",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código Sequencial",
                    ),
                ),
                (
                    "termo_aditivo_numero_termo_aditivo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número do Termo Aditivo",
                    ),
                ),
                (
                    "termo_aditivo_data_assinatura",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Assinatura"
                    ),
                ),
                (
                    "termo_aditivo_data_inicio_vigencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Início de Vigência"
                    ),
                ),
                (
                    "termo_aditivo_data_termino_vigencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Término de Vigência"
                    ),
                ),
                (
                    "data_termo_aditivo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Termo Aditivo"
                    ),
                ),
                (
                    "valor_aditado_concedente_contratado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Valor Aditado Concedente",
                    ),
                ),
                (
                    "valor_aditado_proponente_contratado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Valor Aditado Proponente",
                    ),
                ),
                (
                    "termo_aditivo_justificativa",
                    models.TextField(
                        blank=True, null=True, verbose_name="Justificativa"
                    ),
                ),
                (
                    "termo_aditivo_ano",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ano"
                    ),
                ),
                (
                    "termo_aditivo_alteracao",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Alteração"
                    ),
                ),
                (
                    "termo_aditivo_tipo",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Tipo"
                    ),
                ),
                (
                    "tipo_termo_aditivo",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tipo (alt.)",
                    ),
                ),
                (
                    "quantidade_termo_aditivo",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Quantidade"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Termo Aditivo",
                "verbose_name_plural": "Termos Aditivos",
                "indexes": [
                    models.Index(
                        fields=["termo_aditivo_codigo_sequencial"],
                        name="termo_aditivo_codigo_idx",
                    )
                ],
            },
        ),
    ]
