# Generated by Django 6.0.6 on 2026-06-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "convenios",
            "0003_esfera_codigoconvenio_codigodeclaracaocontrapartida_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="convenio",
            name="cnpj_concedente",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="CNPJ Concedente"
            ),
        ),
        migrations.AddField(
            model_name="convenio",
            name="cnpj_proponente",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="CNPJ Proponente"
            ),
        ),
        migrations.AddField(
            model_name="convenio",
            name="concedente",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Concedente"
            ),
        ),
        migrations.AddField(
            model_name="convenio",
            name="convenio_ano",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Ano"
            ),
        ),
        migrations.AddField(
            model_name="convenio",
            name="data_assinatura",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Assinatura"
            ),
        ),
        migrations.AddField(
            model_name="convenio",
            name="data_publicacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Publicação"
            ),
        ),
        migrations.AddField(
            model_name="convenio",
            name="esfera",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Esfera"
            ),
        ),
        migrations.AddField(
            model_name="convenio",
            name="instrumento",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Instrumento"
            ),
        ),
        migrations.AddField(
            model_name="convenio",
            name="objeto",
            field=models.TextField(blank=True, null=True, verbose_name="Objeto"),
        ),
        migrations.AddField(
            model_name="convenio",
            name="plano_trabalho_codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="Código Plano de Trabalho",
            ),
        ),
        migrations.AddField(
            model_name="convenio",
            name="titulo",
            field=models.TextField(blank=True, null=True, verbose_name="Título"),
        ),
        migrations.AddField(
            model_name="cronogramadesembolso",
            name="convenio_numero_sequencial_siafi",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código SIAFI"
            ),
        ),
        migrations.AddField(
            model_name="cronogramadesembolso",
            name="unidade_orcamentaria_codigo",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Cód. UO"
            ),
        ),
        migrations.AlterField(
            model_name="convenio",
            name="convenio_codigo",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Código SIGCON"
            ),
        ),
        migrations.AlterField(
            model_name="convenio",
            name="convenio_numero_sequencial_siafi",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código SIAFI"
            ),
        ),
        migrations.AlterField(
            model_name="convenio",
            name="unidade_orcamentaria_codigo",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Cód. UO"
            ),
        ),
        migrations.AlterField(
            model_name="cronogramadesembolso",
            name="ano_cronograma_desembolso",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Ano"
            ),
        ),
        migrations.AlterField(
            model_name="cronogramadesembolso",
            name="mes_cronograma_desembolso",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Mês"
            ),
        ),
        migrations.AddIndex(
            model_name="convenio",
            index=models.Index(
                fields=[
                    "convenio_numero_sequencial_siafi",
                    "unidade_orcamentaria_codigo",
                ],
                name="convenios_chave_composta_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cronogramadesembolso",
            index=models.Index(
                fields=[
                    "convenio_numero_sequencial_siafi",
                    "unidade_orcamentaria_codigo",
                ],
                name="cronograma_chave_composta_idx",
            ),
        ),
    ]
