# Generated by Django 6.0.6 on 2026-06-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convenios", "0004_convenio_consolidado_cronograma_siafi"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConvenioIntegrado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "siafi_uo",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="SIAFI_UO",
                    ),
                ),
                (
                    "siafi_uo_atual",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=30,
                        null=True,
                        verbose_name="SIAFI_UO Atual",
                    ),
                ),
                (
                    "convenio_numero_sequencial_siafi",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Nr. SIAFI"
                    ),
                ),
                (
                    "unidade_orcamentaria_codigo",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Cód. UO"
                    ),
                ),
                (
                    "siafiatual",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="SIAFI Atual"
                    ),
                ),
                (
                    "uo_atual",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="UO Atual"
                    ),
                ),
                (
                    "codigo_siconv",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Cód. SICONV"
                    ),
                ),
                (
                    "instrumento_chaves",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Instrumento (chaves)",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Situação (chaves)",
                    ),
                ),
                (
                    "situacao_std",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Situação Padronizada",
                    ),
                ),
                (
                    "uo_nome_std",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nome UO"
                    ),
                ),
                (
                    "uo_sigla_std",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Sigla UO"
                    ),
                ),
                (
                    "uo_descricao_std",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descrição UO",
                    ),
                ),
                (
                    "g_dia_assinatura",
                    models.DateField(
                        blank=True, null=True, verbose_name="G_ Data Assinatura"
                    ),
                ),
                (
                    "g_inicio_vigencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="G_ Início Vigência"
                    ),
                ),
                (
                    "g_fim_vigencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="G_ Fim Vigência"
                    ),
                ),
                (
                    "g_fim_vigencia_inicial",
                    models.DateField(
                        blank=True, null=True, verbose_name="G_ Fim Vigência Inicial"
                    ),
                ),
                (
                    "g_ano_assinatura",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="G_ Ano Assinatura"
                    ),
                ),
                (
                    "g_ano_inicio_vigencia",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="G_ Ano Início Vigência"
                    ),
                ),
                (
                    "g_ano_convenio",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="G_ Ano Convênio"
                    ),
                ),
                (
                    "g_situacao_convenio",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="G_ Situação",
                    ),
                ),
                (
                    "g_objeto_convenio",
                    models.TextField(blank=True, null=True, verbose_name="G_ Objeto"),
                ),
                (
                    "g_proponente",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="G_ Proponente",
                    ),
                ),
                (
                    "g_concedente",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="G_ Concedente",
                    ),
                ),
                (
                    "g_instrumento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="G_ Instrumento",
                    ),
                ),
                (
                    "g_esfera",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="G_ Esfera"
                    ),
                ),
                (
                    "g_uo",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="G_ UO"
                    ),
                ),
                (
                    "g_vigencia",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="G_ Vigência"
                    ),
                ),
                (
                    "g_situacao_convenio_categorizado",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="G_ Situação Categorizada",
                    ),
                ),
                (
                    "g_concedente_pad",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="G_ Concedente Pad.",
                    ),
                ),
                (
                    "g_proponente_pad",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="G_ Proponente Pad.",
                    ),
                ),
                (
                    "g_proponente_pad_siglas",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="G_ Proponente Siglas",
                    ),
                ),
                (
                    "g_uo_descricao",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="G_ Descrição UO",
                    ),
                ),
                (
                    "g_valor_concedente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="G_ Valor Concedente",
                    ),
                ),
                (
                    "g_valor_proponente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="G_ Valor Proponente",
                    ),
                ),
                (
                    "g_valor_global",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="G_ Valor Global",
                    ),
                ),
                (
                    "g_periodo_nao_aditado",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="G_ Período Não Aditado"
                    ),
                ),
                (
                    "g_valor_nao_aditado",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="G_ Valor Não Aditado"
                    ),
                ),
                (
                    "limpeza_g",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Limpeza G_"
                    ),
                ),
                (
                    "a_dia_assinatura",
                    models.DateField(
                        blank=True, null=True, verbose_name="A_ Data Assinatura"
                    ),
                ),
                (
                    "a_inicio_vigencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="A_ Início Vigência"
                    ),
                ),
                (
                    "a_fim_vigencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="A_ Fim Vigência"
                    ),
                ),
                (
                    "a_fim_vigencia_inicial",
                    models.DateField(
                        blank=True, null=True, verbose_name="A_ Fim Vigência Inicial"
                    ),
                ),
                (
                    "a_ano_assinatura",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="A_ Ano Assinatura"
                    ),
                ),
                (
                    "a_ano_inicio_vigencia",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="A_ Ano Início Vigência"
                    ),
                ),
                (
                    "a_ano_convenio",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="A_ Ano Convênio"
                    ),
                ),
                (
                    "a_situacao_convenio",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="A_ Situação",
                    ),
                ),
                (
                    "a_objeto_convenio",
                    models.TextField(blank=True, null=True, verbose_name="A_ Objeto"),
                ),
                (
                    "a_proponente",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="A_ Proponente",
                    ),
                ),
                (
                    "a_concedente",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="A_ Concedente",
                    ),
                ),
                (
                    "a_instrumento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="A_ Instrumento",
                    ),
                ),
                (
                    "a_esfera",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="A_ Esfera"
                    ),
                ),
                (
                    "a_vigencia",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="A_ Vigência"
                    ),
                ),
                (
                    "a_situacao_convenio_categorizado",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="A_ Situação Categorizada",
                    ),
                ),
                (
                    "a_concedente_pad",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="A_ Concedente Pad.",
                    ),
                ),
                (
                    "a_proponente_pad",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="A_ Proponente Pad.",
                    ),
                ),
                (
                    "a_proponente_pad_siglas",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="A_ Proponente Siglas",
                    ),
                ),
                (
                    "a_valor_concedente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="A_ Valor Concedente",
                    ),
                ),
                (
                    "a_valor_proponente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="A_ Valor Proponente",
                    ),
                ),
                (
                    "a_valor_global",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="A_ Valor Global",
                    ),
                ),
                (
                    "a_periodo_nao_aditado",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="A_ Período Não Aditado"
                    ),
                ),
                (
                    "a_valor_nao_aditado",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="A_ Valor Não Aditado"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Convênio Integrado",
                "verbose_name_plural": "Convênios Integrados",
                "ordering": ["-g_fim_vigencia"],
                "indexes": [
                    models.Index(
                        fields=["siafi_uo_atual"], name="conv_int_siafi_atual_idx"
                    ),
                    models.Index(
                        fields=["g_situacao_convenio_categorizado"],
                        name="conv_int_sit_cat_idx",
                    ),
                    models.Index(fields=["g_vigencia"], name="conv_int_vigencia_idx"),
                    models.Index(
                        fields=["g_fim_vigencia"], name="conv_int_fim_vig_idx"
                    ),
                    models.Index(fields=["g_ano_convenio"], name="conv_int_ano_idx"),
                ],
            },
        ),
    ]
