# Generated by Django 6.0.6 on 2026-06-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convenios", "0006_controle_sei"),
    ]

    operations = [
        migrations.AddField(
            model_name="cronogramadesembolso",
            name="convenio_codigo",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código SIGCON"
            ),
        ),
        migrations.AddField(
            model_name="planoaplicacao",
            name="convenio_codigo",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código SIGCON"
            ),
        ),
        migrations.AddIndex(
            model_name="cronogramadesembolso",
            index=models.Index(
                fields=["convenio_codigo"], name="cronograma_convenio_codigo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planoaplicacao",
            index=models.Index(
                fields=["convenio_codigo"], name="plano_apl_conv_codigo_idx"
            ),
        ),
    ]
