# Generated by Django 6.0.6 on 2026-09-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convenios", "0008_planoaplicacao_convenio_numero_sequencial_siafi"),
    ]

    operations = [
        migrations.CreateModel(
            name="CronogramaDesembolsoGrp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Número GRP"
                    ),
                ),
                (
                    "parcela_desembolso",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Parcela do Desembolso",
                    ),
                ),
                (
                    "mes_desembolso",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Mês do Desembolso",
                    ),
                ),
                (
                    "ano_desembolso",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Ano do Desembolso",
                    ),
                ),
                (
                    "origem_recurso_parcela",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Origem do Recurso da Parcela",
                    ),
                ),
                (
                    "vl_desembolso",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Valor do Desembolso",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "GRP — Cronograma de Desembolso",
                "verbose_name_plural": "GRP — Cronogramas de Desembolso",
                "indexes": [
                    models.Index(fields=["nr_grp"], name="grp_cronograma_codigo_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="DadosGrp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Número GRP"
                    ),
                ),
                (
                    "nr_instrumento",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número Instrumento",
                    ),
                ),
                (
                    "uo_cod",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Código UO"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Situação"
                    ),
                ),
                (
                    "dt_vigencia_inicial",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Vigência Inicial"
                    ),
                ),
                (
                    "dt_vigencia_termino",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Vigência Término"
                    ),
                ),
                (
                    "dt_vigenciainicial_termino",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data Vigência Inicial Término",
                    ),
                ),
                (
                    "vl_instrumento_concedente_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Valor Instrumento Concedente Inicial",
                    ),
                ),
                (
                    "vl_instrumento_concedente",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Valor Instrumento Concedente",
                    ),
                ),
                (
                    "vl_instrumento_contrapartida_fin_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Valor Instrumento Contrapartida Financeira Inicial",
                    ),
                ),
                (
                    "vl_instrumento_contrapartida_fin",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Valor Instrumento Contrapartida Financeira",
                    ),
                ),
                (
                    "vl_instrumento_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Valor Instrumento Total",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "GRP — Dados Gerais",
                "verbose_name_plural": "GRP — Dados Gerais",
                "indexes": [
                    models.Index(fields=["nr_grp"], name="grp_geral_codigo_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="EsferaGrp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concedente_nome",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome do Concedente",
                    ),
                ),
                (
                    "concedente_cnpj",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="CNPJ do Concedente",
                    ),
                ),
                (
                    "concedente_esfera",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Esfera"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Esfera do Concedente",
                "verbose_name_plural": "Esferas dos Concedentes",
                "indexes": [
                    models.Index(
                        fields=["concedente_cnpj"], name="esfera_concedente_cnpj_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanoAplicacaoGrp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Número GRP"
                    ),
                ),
                (
                    "nome_projeto",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nome do Projeto",
                    ),
                ),
                (
                    "objeto_projeto",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Objeto do Projeto",
                    ),
                ),
                (
                    "situacao_instrumento",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Situação do Instrumento",
                    ),
                ),
                (
                    "tipo_instrumento",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Tipo do Instrumento",
                    ),
                ),
                (
                    "responsavel_nome",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nome do Responsável",
                    ),
                ),
                (
                    "responsavel_atribuicao",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Atribuição do Responsável",
                    ),
                ),
                (
                    "cnpj_convenente",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="CNPJ do Convenente",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "GRP — Plano de Aplicação",
                "verbose_name_plural": "GRP — Planos de Aplicação",
                "indexes": [
                    models.Index(fields=["nr_grp"], name="grp_plano_codigo_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanoAplicacaoGrpDetalhes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_catmas",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número CATMAS",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Número GRP"
                    ),
                ),
                (
                    "tipo_despesa",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Tipo de Despesa",
                    ),
                ),
                (
                    "categoria_despesa",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Categoria de Despesa",
                    ),
                ),
                (
                    "grupo_despesa",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Grupo de Despesa",
                    ),
                ),
                (
                    "modalidade",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Modalidade"
                    ),
                ),
                (
                    "elemento_despesa",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Elemento de Despesa",
                    ),
                ),
                (
                    "beneficiario_cnpj",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="CNPJ do Beneficiário",
                    ),
                ),
                (
                    "descricao_item",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Descrição do Item a executar",
                    ),
                ),
                (
                    "origem_recurso",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Origem do Recurso",
                    ),
                ),
                (
                    "qt_item_executar",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Quantidade do Item a executar",
                    ),
                ),
                (
                    "vl_uni_item_a_executar",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Valor Unitário do Item a executar",
                    ),
                ),
                (
                    "vl_total_item_a_executar",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Valor Total do Item a executar",
                    ),
                ),
                (
                    "situacao_item_a_executar",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Situação do Item a executar",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "GRP — Detalhes do Plano de Aplicação",
                "verbose_name_plural": "GRP — Detalhes dos Planos de Aplicação",
                "indexes": [
                    models.Index(fields=["nr_grp"], name="grp_plano_detalhe_codigo_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="RecursosConcedenteGrp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uo_cod",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Código UO"
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Número GRP"
                    ),
                ),
                (
                    "fonte",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Fonte Recurso",
                    ),
                ),
                (
                    "ipu",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="IPU"
                    ),
                ),
                (
                    "vl_concedente",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Valor Concedente"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "GRP — Recursos do Concedente",
                "verbose_name_plural": "GRP — Recursos do Concedente",
                "indexes": [
                    models.Index(
                        fields=["nr_grp"], name="grp_recurso_concedente_codigo_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RecursosContrapartidaGrp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uo_cod",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Código UO"
                    ),
                ),
                (
                    "fonte",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Fonte Recurso",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Número GRP"
                    ),
                ),
                (
                    "ipu",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="IPU"
                    ),
                ),
                (
                    "vl_contrapartida_financeira",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Valor Contrapartida financeira",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "GRP — Recursos de Contrapartida",
                "verbose_name_plural": "GRP — Recursos de Contrapartida",
                "indexes": [
                    models.Index(
                        fields=["nr_grp"], name="grp_recurso_contrapartida_codigo_idx"
                    )
                ],
            },
        ),
    ]
