# Generated by Django 6.0.6 on 2026-09-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convenios", "0009_cronogramadesembolsogrp_dadosgrp_esferagrp_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="recursosconcedentegrp",
            new_name="grp_recurso_conc_idx",
            old_name="grp_recurso_concedente_codigo_idx",
        ),
        migrations.RenameIndex(
            model_name="recursoscontrapartidagrp",
            new_name="grp_recurso_contr_idx",
            old_name="grp_recurso_contrapartida_codigo_idx",
        ),
        migrations.AlterField(
            model_name="cronogramadesembolsogrp",
            name="vl_desembolso",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="Valor do Desembolso",
            ),
        ),
        migrations.AlterField(
            model_name="dadosgrp",
            name="vl_instrumento_concedente",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="Valor Instrumento Concedente",
            ),
        ),
        migrations.AlterField(
            model_name="dadosgrp",
            name="vl_instrumento_concedente_inicial",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="Valor Instrumento Concedente Inicial",
            ),
        ),
        migrations.AlterField(
            model_name="dadosgrp",
            name="vl_instrumento_contrapartida_fin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="Valor Instrumento Contrapartida Financeira",
            ),
        ),
        migrations.AlterField(
            model_name="dadosgrp",
            name="vl_instrumento_contrapartida_fin_inicial",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="Valor Instrumento Contrapartida Financeira Inicial",
            ),
        ),
        migrations.AlterField(
            model_name="dadosgrp",
            name="vl_instrumento_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="Valor Instrumento Total",
            ),
        ),
        migrations.AlterField(
            model_name="planoaplicacaogrpdetalhes",
            name="qt_item_executar",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Quantidade do Item a executar"
            ),
        ),
        migrations.AlterField(
            model_name="planoaplicacaogrpdetalhes",
            name="vl_total_item_a_executar",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="Valor Total do Item a executar",
            ),
        ),
        migrations.AlterField(
            model_name="planoaplicacaogrpdetalhes",
            name="vl_uni_item_a_executar",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="Valor Unitário do Item a executar",
            ),
        ),
        migrations.AlterField(
            model_name="recursosconcedentegrp",
            name="vl_concedente",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="Valor Concedente",
            ),
        ),
        migrations.AlterField(
            model_name="recursoscontrapartidagrp",
            name="vl_contrapartida_financeira",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="Valor Contrapartida financeira",
            ),
        ),
    ]
