# Generated by Django 6.0.6 on 2026-09-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "convenios",
            "0010_rename_grp_recurso_concedente_codigo_idx_grp_recurso_conc_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="planoaplicacaogrp",
            name="nome_projeto",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nome do Projeto"
            ),
        ),
        migrations.AlterField(
            model_name="planoaplicacaogrp",
            name="objeto_projeto",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Objeto do Projeto"
            ),
        ),
        migrations.AlterField(
            model_name="planoaplicacaogrpdetalhes",
            name="descricao_item",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Descrição do Item a executar",
            ),
        ),
        migrations.AlterField(
            model_name="planoaplicacaogrpdetalhes",
            name="qt_item_executar",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="Quantidade do Item a executar",
            ),
        ),
    ]
