# Generated by Django 6.0.6 on 2026-09-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("convenios", "0011_alter_planoaplicacaogrp_nome_projeto_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cronogramadesembolsogrp",
            name="grp_cronograma_codigo_idx",
        ),
        migrations.DeleteModel(
            name="CronogramaDesembolsoGrp",
        ),
        migrations.RemoveIndex(
            model_name="dadosgrp",
            name="grp_geral_codigo_idx",
        ),
        migrations.DeleteModel(
            name="DadosGrp",
        ),
        migrations.RemoveIndex(
            model_name="esferagrp",
            name="esfera_concedente_cnpj_idx",
        ),
        migrations.DeleteModel(
            name="EsferaGrp",
        ),
        migrations.RemoveIndex(
            model_name="planoaplicacaogrp",
            name="grp_plano_codigo_idx",
        ),
        migrations.DeleteModel(
            name="PlanoAplicacaoGrp",
        ),
        migrations.RemoveIndex(
            model_name="planoaplicacaogrpdetalhes",
            name="grp_plano_detalhe_codigo_idx",
        ),
        migrations.DeleteModel(
            name="PlanoAplicacaoGrpDetalhes",
        ),
        migrations.RemoveIndex(
            model_name="recursosconcedentegrp",
            name="grp_recurso_conc_idx",
        ),
        migrations.DeleteModel(
            name="RecursosConcedenteGrp",
        ),
        migrations.RemoveIndex(
            model_name="recursoscontrapartidagrp",
            name="grp_recurso_contr_idx",
        ),
        migrations.DeleteModel(
            name="RecursosContrapartidaGrp",
        ),
    ]
