"""De-para da fonte grp_instrumento: nome da coluna no GRP -> nome final na silver.
Gerado a partir do Modelo de Extração GRP v1.1, usando os cabeçalhos REAIS do arquivo extraído."""

MAPA_GRP_INSTRUMENTO = {
    'Número InstrumentoGRP'                                  : "nr_grp",
    'Autorização Uso Rendimento S/N'                         : "fl_autorizacao_uso_rendimento",
    'Capacidade TécnicaGerencial'                            : "tx_capacidade_tecnica_gerencial",
    'CartãoConvênio S/N'                                     : "fl_cartao_convenio",
    'CategoriaProjeto 1'                                     : "ds_categoria_projeto_1",
    'CategoriaProjeto 2'                                     : "ds_categoria_projeto_2",
    'CategoriaProjeto 3'                                     : "ds_categoria_projeto_3",
    'Código Proposta'                                        : "cd_proposta",
    'Código PropostaOrigem'                                  : "cd_proposta_origem",
    'Contrapartida Depositada S/N'                           : "fl_contrapartida_depositada",
    'Contrato Repasse'                                       : "nr_contrato_repasse",
    'Contrato Repasse S/N'                                   : "fl_contrato_repasse",
    'ConvenenteInstrumento - CNPJ-CAPJ'                      : "nr_cnpj_convenente",
    'ConvenenteInstrumento - Nome'                           : "nm_convenente",
    'Convênio Restrito S/N'                                  : "fl_convenio_restrito",
    'Data Assinatura Instrumento'                            : "dt_assinatura",
    'Data Publicação Instrumento'                            : "dt_publicacao",
    'Data VigênciaInicial Instrumento - Término'             : "dt_vigencia_termino_inicial",
    'Data Vigência Instrumento - Inicio'                     : "dt_vigencia_inicio",
    'Data Vigência Instrumento - Término'                    : "dt_vigencia_termino",
    'EmendaParlamentar S/N'                                  : "fl_emenda_parlamentar",
    'Financiamento DespesaPessoal S/N'                       : "fl_financiamento_despesa_pessoal",
    'Instrumento Financiador S/N'                            : "fl_instrumento_financiador",
    'IntervenienteExecutor S/N'                              : "fl_interveniente_executor",
    'Justificativa Instrumento'                              : "tx_justificativa_instrumento",
    'Justificativa Restrição'                                : "tx_justificativa_restricao",
    'Mandatária - CNPJ'                                      : "nr_cnpj_mandataria",
    'Mandatária - Nome'                                      : "nm_mandataria",
    'Nome Projeto'                                           : "nm_projeto",
    'Número Instrumento'                                     : "nr_instrumento",
    'Número Instrumento+Brasil'                              : "nr_instrumento_transferegov",
    'Número Proposta/Instrumento'                            : "nr_proposta_instrumento",
    'Número Proposta+Brasil'                                 : "nr_proposta_transferegov",
    'Número SEI 1'                                           : "nr_sei_1",
    'Número SEI 2'                                           : "nr_sei_2",
    'Número SEI 3'                                           : "nr_sei_3",
    'Número SEI 4'                                           : "nr_sei_4",
    'Número SEI 5'                                           : "nr_sei_5",
    'Objeto Projeto'                                         : "tx_objeto_projeto",
    'OBTV S/N'                                               : "fl_obtv",
    'Proponente/ConvenenteGRP - CNPJ-CAPJ'                   : "nr_cnpj_proponente",
    'Proponente/ConvenenteGRP - Nome'                        : "nm_proponente",
    'Relação Projeto AçãoOrçamentária'                       : "tx_relacao_projeto_acao",
    'Situação Instrumento'                                   : "ds_situacao_instrumento",
    'Situação Proposta'                                      : "ds_situacao_proposta",
    'Tipo InstrumentoJurídico - Código'                      : "cd_tipo_instrumento_juridico",
    'Tipo InstrumentoJurídico - Descrição'                   : "ds_tipo_instrumento_juridico",
    'Tipo Proposta'                                          : "tp_proposta",
    'Tipo Proposta/Instrumento'                              : "tp_proposta_instrumento",
    'Tipo Transferência'                                     : "tp_transferencia",
    'Validação ItemDespesa S/N'                              : "fl_validacao_item_despesa",
    'Validação Vigência Execução S/N'                        : "fl_validacao_vigencia_execucao",
    'Valor Instrumento - Concedente'                         : "vl_instrumento_concedente",
    'Valor Instrumento - Concedente Executado'               : "vl_instrumento_concedente_executado",
    'Valor Instrumento - Concedente Executado Inicial'       : "vl_instrumento_concedente_executado_inicial",
    'Valor Instrumento - Concedente Inicial'                 : "vl_instrumento_concedente_inicial",
    'Valor Instrumento - Contrapartida Financeira'           : "vl_instrumento_contrapartida_fin",
    'Valor Instrumento - Contrapartida Financeira Inicial'   : "vl_instrumento_contrapartida_fin_inicial",
    'Valor Instrumento - Contrapartida nãoFinanceira'        : "vl_instrumento_contrapartida_nao_fin",
    'Valor Instrumento - Contrapartida nãoFinanceira Inicial': "vl_instrumento_contrapartida_nao_fin_inicial",
    'Valor Instrumento - Total'                              : "vl_instrumento_total",
    'Valor Instrumento - Total Inicial'                      : "vl_instrumento_total_inicial",
    'Valor Proposta - Concedente'                            : "vl_proposta_concedente",
    'Valor Proposta - Concedente Executado'                  : "vl_proposta_concedente_executado",
    'Valor Proposta - Contrapartida Financeira'              : "vl_proposta_contrapartida_fin",
    'Valor Proposta - Contrapartida nãoFinanceira'           : "vl_proposta_contrapartida_nao_fin",
    'Valor Proposta - Total'                                 : "vl_proposta_total",
    'Valor Rendimento Autorizado'                            : "vl_rendimento_autorizado",
}
