# Generated by Django 6.0.6 on 2026-09-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TabelaUoGrp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uo_cod",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Código UO"
                    ),
                ),
                (
                    "uo_nome",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nome da UO"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "GRP — Tabela de Unidades Orçamentárias",
                "verbose_name_plural": "GRP — Tabelas de Unidades Orçamentárias",
                "db_table": "convenios_tabelauogrp",
                "indexes": [
                    models.Index(fields=["uo_cod"], name="grp_tabela_uo_codigo_idx")
                ],
            },
        ),
    ]
