# Generated by Django 6.0.6 on 2026-09-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grp", "0003_alter_planoaplicacaogrpdetalhes_descricao_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planoaplicacaogrpdetalhes",
            name="descricao_item",
            field=models.CharField(
                blank=True,
                max_length=5000,
                null=True,
                verbose_name="Descrição do Item a executar",
            ),
        ),
    ]
