# Generated by Django 6.0.6 on 2026-10-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grp", "0004_alter_planoaplicacaogrpdetalhes_descricao_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrpInstrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tp_proposta_instrumento", models.TextField(blank=True, null=True)),
                (
                    "nr_proposta_instrumento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nr_cnpj_proponente",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                ("nm_proponente", models.TextField(blank=True, null=True)),
                ("nm_projeto", models.TextField(blank=True, null=True)),
                (
                    "nr_grp",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "nr_instrumento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nr_instrumento_transferegov",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cd_proposta_origem",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cd_tipo_instrumento_juridico",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ds_tipo_instrumento_juridico",
                    models.TextField(blank=True, null=True),
                ),
                ("ds_situacao_instrumento", models.TextField(blank=True, null=True)),
                (
                    "cd_proposta",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("tp_proposta", models.TextField(blank=True, null=True)),
                (
                    "nr_proposta_transferegov",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ds_situacao_proposta", models.TextField(blank=True, null=True)),
                ("tx_objeto_projeto", models.TextField(blank=True, null=True)),
                ("nr_sei_1", models.CharField(blank=True, max_length=100, null=True)),
                ("nr_sei_2", models.CharField(blank=True, max_length=100, null=True)),
                ("nr_sei_3", models.CharField(blank=True, max_length=100, null=True)),
                ("nr_sei_4", models.CharField(blank=True, max_length=100, null=True)),
                ("nr_sei_5", models.CharField(blank=True, max_length=100, null=True)),
                ("ds_categoria_projeto_1", models.TextField(blank=True, null=True)),
                ("ds_categoria_projeto_2", models.TextField(blank=True, null=True)),
                ("ds_categoria_projeto_3", models.TextField(blank=True, null=True)),
                (
                    "fl_interveniente_executor",
                    models.BooleanField(blank=True, null=True),
                ),
                ("fl_emenda_parlamentar", models.BooleanField(blank=True, null=True)),
                (
                    "fl_instrumento_financiador",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "tx_capacidade_tecnica_gerencial",
                    models.TextField(blank=True, null=True),
                ),
                ("tx_relacao_projeto_acao", models.TextField(blank=True, null=True)),
                ("fl_convenio_restrito", models.BooleanField(blank=True, null=True)),
                ("tx_justificativa_restricao", models.TextField(blank=True, null=True)),
                (
                    "vl_proposta_concedente",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_proposta_contrapartida_fin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_proposta_contrapartida_nao_fin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_proposta_concedente_executado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_proposta_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_instrumento_concedente_inicial",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_instrumento_contrapartida_fin_inicial",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_instrumento_contrapartida_nao_fin_inicial",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_instrumento_concedente_executado_inicial",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_instrumento_total_inicial",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_instrumento_concedente",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_instrumento_contrapartida_fin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_instrumento_contrapartida_nao_fin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_instrumento_concedente_executado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_instrumento_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_rendimento_autorizado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "nr_cnpj_convenente",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                ("nm_convenente", models.TextField(blank=True, null=True)),
                (
                    "tx_justificativa_instrumento",
                    models.TextField(blank=True, null=True),
                ),
                ("dt_assinatura", models.DateField(blank=True, null=True)),
                ("dt_publicacao", models.DateField(blank=True, null=True)),
                ("dt_vigencia_inicio", models.DateField(blank=True, null=True)),
                ("dt_vigencia_termino", models.DateField(blank=True, null=True)),
                (
                    "dt_vigencia_termino_inicial",
                    models.DateField(blank=True, null=True),
                ),
                ("fl_contrato_repasse", models.BooleanField(blank=True, null=True)),
                (
                    "nr_contrato_repasse",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nr_cnpj_mandataria",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                ("nm_mandataria", models.TextField(blank=True, null=True)),
                ("tp_transferencia", models.TextField(blank=True, null=True)),
                ("fl_obtv", models.BooleanField(blank=True, null=True)),
                (
                    "fl_contrapartida_depositada",
                    models.BooleanField(blank=True, null=True),
                ),
                ("fl_cartao_convenio", models.BooleanField(blank=True, null=True)),
                (
                    "fl_validacao_vigencia_execucao",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "fl_validacao_item_despesa",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "fl_financiamento_despesa_pessoal",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "fl_autorizacao_uso_rendimento",
                    models.BooleanField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Instrumento GRP",
                "verbose_name_plural": "Instrumentos GRP",
                "db_table": "grp_instrumento",
                "ordering": ["nr_grp"],
            },
        ),
    ]
