# Generated by Django 6.0.6 on 2026-10-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grp", "0005_grpinstrumento"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrpConcedente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "nr_cnpj_concedente",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        verbose_name="CNPJ do Concedente",
                    ),
                ),
                (
                    "nm_concedente",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome do Concedente",
                    ),
                ),
                (
                    "ds_esfera_atuacao",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Esfera de Atuação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concedente GRP",
                "verbose_name_plural": "Concedentes GRP",
                "db_table": "grp_concedente",
                "ordering": ["nr_grp"],
            },
        ),
    ]
