# Generated by Django 6.0.6 on 2026-10-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grp", "0006_grpconcedente"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrpAcaoOrcamentaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                ("cd_acao", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cd_uo_execucao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nm_uo_execucao", models.TextField(blank=True, null=True)),
                (
                    "sg_uo_execucao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ds_situacao_acao", models.TextField(blank=True, null=True)),
                (
                    "vl_execucao_orcamentaria",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "cd_orgao_gestor_execucao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nm_orgao_gestor_execucao", models.TextField(blank=True, null=True)),
                (
                    "sg_orgao_gestor_execucao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Acao Orcamentaria GRP",
                "verbose_name_plural": "Acao Orcamentaria GRP",
                "db_table": "grp_acao_orcamentaria",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpAtividadeProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                ("tx_atividade", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Atividade Projeto GRP",
                "verbose_name_plural": "Atividade Projeto GRP",
                "db_table": "grp_atividade_projeto",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpCronogramaDesembolso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                ("nr_parcela", models.CharField(blank=True, max_length=100, null=True)),
                ("ds_origem_recurso_parcela", models.TextField(blank=True, null=True)),
                (
                    "nr_ano_desembolso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nr_mes_desembolso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vl_desembolso",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Cronograma Desembolso GRP",
                "verbose_name_plural": "Cronograma Desembolso GRP",
                "db_table": "grp_cronograma_desembolso",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpCronogramaFisico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                ("tp_meta_etapa", models.TextField(blank=True, null=True)),
                ("tx_meta_especificacao", models.TextField(blank=True, null=True)),
                ("dt_meta_inicio", models.DateField(blank=True, null=True)),
                ("dt_meta_termino", models.DateField(blank=True, null=True)),
                ("qt_meta_duracao", models.IntegerField(blank=True, null=True)),
                (
                    "vl_meta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("tx_etapa_especificacao", models.TextField(blank=True, null=True)),
                ("dt_etapa_inicio", models.DateField(blank=True, null=True)),
                ("dt_etapa_termino", models.DateField(blank=True, null=True)),
                ("qt_etapa_duracao", models.IntegerField(blank=True, null=True)),
                (
                    "vl_etapa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Cronograma Fisico GRP",
                "verbose_name_plural": "Cronograma Fisico GRP",
                "db_table": "grp_cronograma_fisico",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpDotacaoContrapartida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "cd_dotacao_contrapartida",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ds_situacao_dotacao", models.TextField(blank=True, null=True)),
                (
                    "vl_dotacao_contrapartida",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Dotacao Contrapartida GRP",
                "verbose_name_plural": "Dotacao Contrapartida GRP",
                "db_table": "grp_dotacao_contrapartida",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpEmenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "nr_ano_emenda",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nr_emenda", models.CharField(blank=True, max_length=100, null=True)),
                ("nm_parlamentar", models.TextField(blank=True, null=True)),
                ("tp_transferencia_emenda", models.TextField(blank=True, null=True)),
                ("ds_situacao_emenda", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Emenda GRP",
                "verbose_name_plural": "Emenda GRP",
                "db_table": "grp_emenda",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpEntregaProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                ("tx_entrega", models.TextField(blank=True, null=True)),
                ("tx_indicador_produto", models.TextField(blank=True, null=True)),
                ("tx_meta_prazo_entrega", models.TextField(blank=True, null=True)),
                (
                    "tx_criterio_aceitacao_entrega",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "tx_meio_verificacao_entrega",
                    models.TextField(blank=True, null=True),
                ),
                ("tx_pressuposto_entrega", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Entrega Projeto GRP",
                "verbose_name_plural": "Entrega Projeto GRP",
                "db_table": "grp_entrega_projeto",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpInstrumentoFinanciado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "nr_instrumento_financiado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tp_instrumento_financiado", models.TextField(blank=True, null=True)),
                (
                    "vl_instrumento_financiado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrumento Financiado GRP",
                "verbose_name_plural": "Instrumento Financiado GRP",
                "db_table": "grp_instrumento_financiado",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpInterveniente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                ("nm_interveniente", models.TextField(blank=True, null=True)),
                (
                    "sg_interveniente",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cd_interveniente",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nr_cnpj_interveniente",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
            ],
            options={
                "verbose_name": "Interveniente GRP",
                "verbose_name_plural": "Interveniente GRP",
                "db_table": "grp_interveniente",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpItemExecutar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                ("cd_catmas", models.CharField(blank=True, max_length=100, null=True)),
                ("tp_despesa", models.TextField(blank=True, null=True)),
                (
                    "nr_cnpj_beneficiario",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                ("ds_item", models.TextField(blank=True, null=True)),
                ("ds_origem_recurso", models.TextField(blank=True, null=True)),
                ("ds_situacao_item", models.TextField(blank=True, null=True)),
                (
                    "qt_item",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_unitario_item",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_total_item",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "cd_categoria_economica",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cd_grupo_despesa",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cd_modalidade_aplicacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cd_elemento_despesa",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cd_elemento_item",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Item Executar GRP",
                "verbose_name_plural": "Item Executar GRP",
                "db_table": "grp_item_executar",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpMatrizResponsabilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                ("tp_gestor_participante", models.TextField(blank=True, null=True)),
                (
                    "cd_unidade_adm_vinculacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nm_unidade_adm_vinculacao", models.TextField(blank=True, null=True)),
                (
                    "sg_unidade_adm_vinculacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nr_cpf_responsavel",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("nm_responsavel", models.TextField(blank=True, null=True)),
                ("ds_nivel_hierarquico", models.TextField(blank=True, null=True)),
                ("ds_atribuicao", models.TextField(blank=True, null=True)),
                ("ds_email_responsavel", models.TextField(blank=True, null=True)),
                (
                    "nr_telefone_responsavel",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "fl_responsavel_monitoramento",
                    models.BooleanField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Matriz Responsabilidade GRP",
                "verbose_name_plural": "Matriz Responsabilidade GRP",
                "db_table": "grp_matriz_responsabilidade",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpMunicipioAtendido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                ("nm_municipio", models.TextField(blank=True, null=True)),
                (
                    "cd_municipio",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sg_uf", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Municipio Atendido GRP",
                "verbose_name_plural": "Municipio Atendido GRP",
                "db_table": "grp_municipio_atendido",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpPlanejamentoObras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "fl_projeto_basico_elaborado",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "fl_projeto_basico_em_elaboracao",
                    models.BooleanField(blank=True, null=True),
                ),
                ("fl_projeto_complementar", models.BooleanField(blank=True, null=True)),
                (
                    "fl_projeto_complementar_em_elaboracao",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "fl_licenciamento_ambiental",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "fl_licenciamento_ambiental_em_obtencao",
                    models.BooleanField(blank=True, null=True),
                ),
                ("fl_titularidade_imovel", models.BooleanField(blank=True, null=True)),
                (
                    "fl_titularidade_imovel_em_regularizacao",
                    models.BooleanField(blank=True, null=True),
                ),
                ("fl_desapropriacao", models.BooleanField(blank=True, null=True)),
                (
                    "ds_desapropriacao_origem_recurso",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "fl_desapropriacao_providencias",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "tx_desapropriacao_providencias",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "ds_competencia_execucao_obra",
                    models.TextField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Planejamento Obras GRP",
                "verbose_name_plural": "Planejamento Obras GRP",
                "db_table": "grp_planejamento_obras",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpPrestacaoContas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                ("fl_pc_obrigatoria", models.BooleanField(blank=True, null=True)),
                (
                    "tx_pc_justificativa_nao_obrigatoriedade",
                    models.TextField(blank=True, null=True),
                ),
                ("qt_pc_prazo", models.IntegerField(blank=True, null=True)),
                ("dt_pc_limite", models.DateField(blank=True, null=True)),
                ("dt_pc_limite_inicial", models.DateField(blank=True, null=True)),
                ("tp_pc_final", models.TextField(blank=True, null=True)),
                ("dt_pc_envio", models.DateField(blank=True, null=True)),
                ("fl_conclusao_objeto", models.BooleanField(blank=True, null=True)),
                (
                    "tx_pc_justificativa_conclusao",
                    models.TextField(blank=True, null=True),
                ),
                ("fl_pc_finalizada", models.BooleanField(blank=True, null=True)),
                (
                    "fl_pendencia_contabilizacao",
                    models.BooleanField(blank=True, null=True),
                ),
                ("dt_pc_finalizacao", models.DateField(blank=True, null=True)),
                (
                    "tx_pc_justificativa_aprovacao",
                    models.TextField(blank=True, null=True),
                ),
                ("ds_pc_situacao_aprovacao", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Prestacao Contas GRP",
                "verbose_name_plural": "Prestacao Contas GRP",
                "db_table": "grp_prestacao_contas",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpPropostaMarcoLogico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                ("tx_interesses_reciprocos", models.TextField(blank=True, null=True)),
                (
                    "tx_relacao_projeto_objetivo",
                    models.TextField(blank=True, null=True),
                ),
                ("tx_publico_alvo", models.TextField(blank=True, null=True)),
                ("tx_problema", models.TextField(blank=True, null=True)),
                ("tx_resultado_esperado", models.TextField(blank=True, null=True)),
                ("tx_objetivo_geral", models.TextField(blank=True, null=True)),
                (
                    "tx_indicadores_objetivo_geral",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "tx_metas_prazo_objetivo_geral",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "tx_criterios_aceitacao_objetivo_geral",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "tx_verificacao_indicadores_objetivo_geral",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "tx_pressupostos_objetivo_geral",
                    models.TextField(blank=True, null=True),
                ),
                ("tx_proposito", models.TextField(blank=True, null=True)),
                ("tx_indicadores_proposito", models.TextField(blank=True, null=True)),
                ("tx_metas_prazo_proposito", models.TextField(blank=True, null=True)),
                (
                    "tx_criterios_aceitacao_proposito",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "tx_verificacao_indicadores_proposito",
                    models.TextField(blank=True, null=True),
                ),
                ("tx_pressupostos_proposito", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Proposta Marco Logico GRP",
                "verbose_name_plural": "Proposta Marco Logico GRP",
                "db_table": "grp_proposta_marco_logico",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpRecursoConcedente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "cd_uo_arrecadacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nm_uo_arrecadacao", models.TextField(blank=True, null=True)),
                (
                    "sg_uo_arrecadacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ds_situacao_recurso_concedente",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "vl_recurso_concedente",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "cd_orgao_gestor_arrecadacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nm_orgao_gestor_arrecadacao",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "sg_orgao_gestor_arrecadacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cd_fonte_recurso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cd_ipu", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Recurso Concedente GRP",
                "verbose_name_plural": "Recurso Concedente GRP",
                "db_table": "grp_recurso_concedente",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpRecursoContrapartida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "cd_uo_financiadora",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nm_uo_financiadora", models.TextField(blank=True, null=True)),
                (
                    "sg_uo_financiadora",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ds_situacao_contrapartida", models.TextField(blank=True, null=True)),
                (
                    "vl_contrapartida_financeira",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "cd_orgao_gestor_financiadora",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nm_orgao_gestor_financiadora",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "sg_orgao_gestor_financiadora",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cd_fonte_recurso_contrapartida",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cd_ipu_contrapartida",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Recurso Contrapartida GRP",
                "verbose_name_plural": "Recurso Contrapartida GRP",
                "db_table": "grp_recurso_contrapartida",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpRegiaoAtendida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                ("nm_regiao", models.TextField(blank=True, null=True)),
                ("cd_regiao", models.CharField(blank=True, max_length=100, null=True)),
                ("ds_situacao_regiao", models.TextField(blank=True, null=True)),
                ("nm_municipio_regiao", models.TextField(blank=True, null=True)),
                (
                    "cd_municipio_regiao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sg_uf_municipio_regiao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Regiao Atendida GRP",
                "verbose_name_plural": "Regiao Atendida GRP",
                "db_table": "grp_regiao_atendida",
                "ordering": ["nr_grp"],
            },
        ),
        migrations.CreateModel(
            name="GrpTabelaUo",
            fields=[
                (
                    "cd_uo",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nm_uo", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tabela Uo GRP",
                "verbose_name_plural": "Tabela Uo GRP",
                "db_table": "grp_tabela_uo",
                "ordering": ["cd_uo"],
            },
        ),
        migrations.CreateModel(
            name="GrpUnidadeExecutora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_grp",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("cd_proposta", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "cd_orgao_unidade_adm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sg_orgao_unidade_adm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nm_orgao_unidade_adm", models.TextField(blank=True, null=True)),
                (
                    "cd_unidade_adm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nm_unidade_adm", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Unidade Executora GRP",
                "verbose_name_plural": "Unidade Executora GRP",
                "db_table": "grp_unidade_executora",
                "ordering": ["nr_grp"],
            },
        ),
    ]
