# Generated by Django 6.0.6 on 2026-10-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grp", "0007_grpacaoorcamentaria_grpatividadeprojeto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grptabelauo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="grptabelauo",
            name="cd_uo",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
