# Generated by Django 6.0.6 on 2026-10-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grp", "0008_grptabelauo_id_alter_grptabelauo_cd_uo"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrpGoldInstrumento",
            fields=[
                (
                    "nr_grp",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "ds_tipo_instrumento_juridico",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "nr_instrumento",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "nr_instrumento_transferegov",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("nm_projeto", models.TextField(blank=True, null=True)),
                ("tx_objeto_projeto", models.TextField(blank=True, null=True)),
                (
                    "nm_convenente",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nm_concedente",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ds_esfera_atuacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ds_situacao_instrumento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dt_assinatura", models.DateField(blank=True, null=True)),
                ("dt_publicacao", models.DateField(blank=True, null=True)),
                ("dt_vigencia_inicio", models.DateField(blank=True, null=True)),
                ("dt_vigencia_termino", models.DateField(blank=True, null=True)),
                (
                    "dt_vigencia_termino_inicial",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "vl_rendimento_autorizado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_instrumento_concedente",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_instrumento_contrapartida_fin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vl_instrumento_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrumento (Gold)",
                "db_table": 'gold"."vw_instrumento',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GrpGoldRecursoConcedente",
            fields=[
                (
                    "nr_grp",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "cd_uo_arrecadacao",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "nm_uo_arrecadacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cd_fonte_recurso",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                ("cd_ipu", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "nm_concedente",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nr_cnpj_concedente",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "vl_recurso_concedente",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "ds_situacao_recurso_concedente",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "Recurso do Concedente (Gold)",
                "db_table": 'gold"."vw_recurso_concedente',
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="grpinstrumento",
            name="ds_origem_instrumento",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grpinstrumento",
            name="ds_origem_proposta",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grpinstrumento",
            name="ds_status_instrumento",
            field=models.TextField(blank=True, null=True),
        ),
    ]
