# Generated by Django 6.0.6 on 2026-06-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_convenio', models.CharField(help_text='Identificador único do convênio (ex: 123456/2024)', max_length=30, unique=True, verbose_name='Nº Convênio')),
                ('nr_processo', models.CharField(blank=True, max_length=50, verbose_name='Nº Processo')),
                ('objeto', models.TextField(verbose_name='Objeto')),
                ('concedente', models.CharField(max_length=255, verbose_name='Concedente')),
                ('convenente', models.CharField(max_length=255, verbose_name='Convenente')),
                ('situacao', models.CharField(max_length=100, verbose_name='Situação')),
                ('valor_global', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Valor Global (R$)')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': 'Convênios',
                'ordering': ['-data_inicio'],
                'indexes': [models.Index(fields=['situacao'], name='convenios_c_situaca_a42817_idx'), models.Index(fields=['concedente'], name='convenios_c_concede_7b0f97_idx'), models.Index(fields=['data_inicio'], name='convenios_c_data_in_24f146_idx')],
            },
        ),
    ]
