# Generated by Django 6.0.6 on 2026-06-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convenios", "0005_conveniointegrado"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControleSEI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "no_sei",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nº SEI",
                    ),
                ),
                (
                    "no_siafi_sigcon",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nº SIAFI (SIGCON)",
                    ),
                ),
                (
                    "no_proposta_siconv",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nº Proposta (SICONV)",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Controle SEI",
                "verbose_name_plural": "Controles SEI",
                "indexes": [
                    models.Index(fields=["no_siafi_sigcon"], name="sei_siafi_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="UnidadesExecutoras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unidade_orcamentaria_codigo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cód. UO",
                    ),
                ),
                (
                    "convenio_numero_sequencial_siafi",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código SIAFI",
                    ),
                ),
                (
                    "unidade_executora",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Unidade Executora",
                    ),
                ),
                (
                    "convenio_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código SIGCON",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Convênio — Unidade Executora",
                "verbose_name_plural": "Convênios — Unidades Executoras",
                "indexes": [
                    models.Index(
                        fields=[
                            "convenio_numero_sequencial_siafi",
                            "unidade_orcamentaria_codigo",
                        ],
                        name="unid_exec_chave_composta_idx",
                    )
                ],
            },
        ),
    ]
