# Generated by Django 6.0.6 on 2026-06-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convenios", "0007_cronogramadesembolso_convenio_codigo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planoaplicacao",
            name="convenio_numero_sequencial_siafi",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código SIAFI"
            ),
        ),
    ]
